### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Doctopus003** [Samuel-Fang/AutomaticCodeCommentGeneration#1]
excuse.
1.When i execute "./test.sh 0,1 CSNpython T5-small CSNpyEx2", there is "ModuleNotFoundError: No module named 'rouge'",but i have installed rouge,and when i excute "python T5Generate.py", there is no such fault.
2.But when i excute "python T5Generate.py"，there is "Unexpected key(s) in state_dict: ......", is it a training model problem?

**Comment by Samuel-Fang** [comment]
@Doctopus003
Hi, thank you for paying attention to this project.

For the first one, can you confirm you have installed rouge in your python lib? if you installed by pip, u can execute `pip show rouge` to see the information of the module.

For the second one, could you please show the full error message so that i can locate where the problem is.

**Comment by Doctopus003** [comment]
1.The first problem should be solved that I reinstalled rouge，
2.But when i excute "python T5Generate.py",the full error message:
**Traceback (most recent call last):
File "T5Generate.py", line 19, in <module>
model.load_state_dict(torch.load(checkpoint_path))
File "/home/user/anaconda3/envs/pytorch_learn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for T5Model:
Unexpected key(s) in state_dict: "lm_head.weight", "decoder.block.0.layer.1.EncDecAttention.relative_attention_bias.weight".**

**Comment by Doctopus003** [comment]
1.The first problem should be solved that I reinstalled rouge，
2.But when i excute "python T5Generate.py",the full error message:
**Traceback (most recent call last):
File "T5Generate.py", line 19, in <module>
model.load_state_dict(torch.load(checkpoint_path))
File "/home/user/anaconda3/envs/pytorch_learn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for T5Model:
Unexpected key(s) in state_dict: "lm_head.weight", "decoder.block.0.layer.1.EncDecAttention.relative_attention_bias.weight".**

**Comment by Doctopus003** [comment]
1.The first problem should be solved that I reinstalled rouge，
2.But when i excute "python T5Generate.py",the full error message:
**Traceback (most recent call last):
File "T5Generate.py", line 19, in <module>
model.load_state_dict(torch.load(checkpoint_path))
File "/home/user/anaconda3/envs/pytorch_learn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for T5Model:
Unexpected key(s) in state_dict: "lm_head.weight", "decoder.block.0.layer.1.EncDecAttention.relative_attention_bias.weight".**

**Comment by Samuel-Fang** [comment]
@Doctopus003
I think it might be the torch version problem. What pytorch version do you use? Maybe it is too new for the checkpoint file. Try reinstall torch 1.4 and do it again.

**Comment by Doctopus003** [comment]
I reinstall torch 1.4，but an error is still reported：
Segmentation fault (core dumped)

**Comment by Samuel-Fang** [comment]
Is this still the error after running T5Generate.py?

This error is caused by a lot of reasons and may related to your running condition like system or hardware.
